"""Tests for spaces resource."""

import pytest
from unittest.mock import patch
from datetime import datetime

from trix import Trix, AsyncTrix
from trix.types import Space, SpaceList


@pytest.fixture
def mock_space_data():
    """Mock space response data."""
    return {
        "id": "space_123",
        "name": "Test Space",
        "slug": "test-space",
        "description": "A test space",
        "created_at": "2025-01-01T00:00:00Z",
        "updated_at": "2025-01-01T00:00:00Z",
    }


@pytest.fixture
def mock_spaces_list_data(mock_space_data):
    """Mock spaces list response data."""
    return {
        "data": [mock_space_data],
    }


class TestSpaceHasSlug:
    """Tests for slug field in Space model."""

    def test_space_has_slug(self, mock_space_data):
        """Test that space includes slug field."""
        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = mock_space_data
            client = Trix(api_key="test_key")

            space = client.spaces.get("space_123")

            assert isinstance(space, Space)
            assert space.slug == "test-space"
            assert space.id == "space_123"
            assert space.name == "Test Space"
            client.close()

    @pytest.mark.asyncio
    async def test_space_has_slug_async(self, mock_space_data):
        """Test that async space includes slug field."""
        with patch.object(AsyncTrix, "_request") as mock_request:
            mock_request.return_value = mock_space_data
            client = AsyncTrix(api_key="test_key")

            space = await client.spaces.get("space_123")

            assert isinstance(space, Space)
            assert space.slug == "test-space"
            await client.close()


class TestCreateWithCustomSlug:
    """Tests for creating spaces with custom slugs."""

    def test_create_with_custom_slug(self, mock_space_data):
        """Test creating space with custom slug."""
        custom_slug_data = mock_space_data.copy()
        custom_slug_data["slug"] = "custom-slug"

        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = custom_slug_data
            client = Trix(api_key="test_key")

            space = client.spaces.create(
                name="Test Space",
                slug="custom-slug",
                description="A test space"
            )

            assert isinstance(space, Space)
            assert space.slug == "custom-slug"
            call_args = mock_request.call_args
            assert call_args[0][0] == "POST"
            assert call_args[0][1] == "/spaces"
            json_data = call_args[1]["json"]
            assert json_data["slug"] == "custom-slug"
            client.close()

    def test_create_without_slug_auto_generated(self, mock_space_data):
        """Test creating space without slug (auto-generated by server)."""
        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = mock_space_data
            client = Trix(api_key="test_key")

            space = client.spaces.create(name="Test Space")

            assert isinstance(space, Space)
            assert space.slug == "test-space"  # Auto-generated from name
            call_args = mock_request.call_args
            json_data = call_args[1]["json"]
            assert "slug" not in json_data  # Not sent when None
            client.close()

    @pytest.mark.asyncio
    async def test_create_with_custom_slug_async(self, mock_space_data):
        """Test async creating space with custom slug."""
        custom_slug_data = mock_space_data.copy()
        custom_slug_data["slug"] = "custom-slug"

        with patch.object(AsyncTrix, "_request") as mock_request:
            mock_request.return_value = custom_slug_data
            client = AsyncTrix(api_key="test_key")

            space = await client.spaces.create(
                name="Test Space",
                slug="custom-slug"
            )

            assert isinstance(space, Space)
            assert space.slug == "custom-slug"
            await client.close()


class TestGetBySlug:
    """Tests for get_by_slug method."""

    def test_get_by_slug(self, mock_space_data):
        """Test getting space by slug."""
        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = mock_space_data
            client = Trix(api_key="test_key")

            space = client.spaces.get_by_slug("test-space")

            assert isinstance(space, Space)
            assert space.id == "space_123"
            assert space.slug == "test-space"
            call_args = mock_request.call_args
            assert call_args[0][0] == "GET"
            assert call_args[0][1] == "/spaces/test-space"
            client.close()

    def test_get_by_slug_empty_raises_error(self):
        """Test that empty slug raises ValueError."""
        with patch.object(Trix, "_request") as mock_request:
            client = Trix(api_key="test_key")

            with pytest.raises(ValueError, match="Slug must be a non-empty string"):
                client.spaces.get_by_slug("")

            client.close()

    @pytest.mark.asyncio
    async def test_get_by_slug_async(self, mock_space_data):
        """Test async getting space by slug."""
        with patch.object(AsyncTrix, "_request") as mock_request:
            mock_request.return_value = mock_space_data
            client = AsyncTrix(api_key="test_key")

            space = await client.spaces.get_by_slug("test-space")

            assert isinstance(space, Space)
            assert space.slug == "test-space"
            await client.close()

    @pytest.mark.asyncio
    async def test_get_by_slug_empty_raises_error_async(self):
        """Test that async empty slug raises ValueError."""
        with patch.object(AsyncTrix, "_request") as mock_request:
            client = AsyncTrix(api_key="test_key")

            with pytest.raises(ValueError, match="Slug must be a non-empty string"):
                await client.spaces.get_by_slug("")

            await client.close()


class TestUpdateSlug:
    """Tests for updating space slug."""

    def test_update_slug(self, mock_space_data):
        """Test updating space slug."""
        updated_data = mock_space_data.copy()
        updated_data["slug"] = "updated-slug"

        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = updated_data
            client = Trix(api_key="test_key")

            space = client.spaces.update("space_123", slug="updated-slug")

            assert isinstance(space, Space)
            assert space.slug == "updated-slug"
            call_args = mock_request.call_args
            assert call_args[0][0] == "PATCH"
            assert call_args[0][1] == "/spaces/space_123"
            json_data = call_args[1]["json"]
            assert json_data["slug"] == "updated-slug"
            client.close()

    def test_update_name_and_slug(self, mock_space_data):
        """Test updating both name and slug."""
        updated_data = mock_space_data.copy()
        updated_data["name"] = "Updated Name"
        updated_data["slug"] = "updated-slug"

        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = updated_data
            client = Trix(api_key="test_key")

            space = client.spaces.update(
                "space_123",
                name="Updated Name",
                slug="updated-slug"
            )

            assert isinstance(space, Space)
            assert space.name == "Updated Name"
            assert space.slug == "updated-slug"
            call_args = mock_request.call_args
            json_data = call_args[1]["json"]
            assert json_data["name"] == "Updated Name"
            assert json_data["slug"] == "updated-slug"
            client.close()

    @pytest.mark.asyncio
    async def test_update_slug_async(self, mock_space_data):
        """Test async updating space slug."""
        updated_data = mock_space_data.copy()
        updated_data["slug"] = "updated-slug"

        with patch.object(AsyncTrix, "_request") as mock_request:
            mock_request.return_value = updated_data
            client = AsyncTrix(api_key="test_key")

            space = await client.spaces.update("space_123", slug="updated-slug")

            assert isinstance(space, Space)
            assert space.slug == "updated-slug"
            await client.close()


class TestSpacesCRUD:
    """Tests for basic CRUD operations on spaces."""

    def test_create_space(self, mock_space_data):
        """Test creating a space."""
        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = mock_space_data
            client = Trix(api_key="test_key")

            space = client.spaces.create(
                name="Test Space",
                description="A test space"
            )

            assert isinstance(space, Space)
            assert space.id == "space_123"
            call_args = mock_request.call_args
            assert call_args[0][0] == "POST"
            assert call_args[0][1] == "/spaces"
            client.close()

    def test_list_spaces(self, mock_spaces_list_data):
        """Test listing spaces."""
        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = mock_spaces_list_data
            client = Trix(api_key="test_key")

            result = client.spaces.list()

            assert isinstance(result, SpaceList)
            assert len(result.data) == 1
            assert result.data[0].slug == "test-space"
            call_args = mock_request.call_args
            assert call_args[0][0] == "GET"
            assert call_args[0][1] == "/spaces"
            client.close()

    def test_get_space(self, mock_space_data):
        """Test getting a space by ID."""
        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = mock_space_data
            client = Trix(api_key="test_key")

            space = client.spaces.get("space_123")

            assert isinstance(space, Space)
            assert space.id == "space_123"
            call_args = mock_request.call_args
            assert call_args[0][1] == "/spaces/space_123"
            client.close()

    def test_delete_space(self):
        """Test deleting a space."""
        with patch.object(Trix, "_request") as mock_request:
            mock_request.return_value = None
            client = Trix(api_key="test_key")

            client.spaces.delete("space_123")

            call_args = mock_request.call_args
            assert call_args[0][0] == "DELETE"
            assert call_args[0][1] == "/spaces/space_123"
            client.close()

    @pytest.mark.asyncio
    async def test_list_spaces_async(self, mock_spaces_list_data):
        """Test async listing spaces."""
        with patch.object(AsyncTrix, "_request") as mock_request:
            mock_request.return_value = mock_spaces_list_data
            client = AsyncTrix(api_key="test_key")

            result = await client.spaces.list()

            assert isinstance(result, SpaceList)
            assert len(result.data) == 1
            assert result.data[0].slug == "test-space"
            await client.close()
