"""Utility modules for Trix SDK."""

from .logging import (
    LogConfig,
    LogFormat,
    LoggerAdapter,
    LogLevel,
    create_logger_adapter,
    get_logger,
    get_request_id,
    log_error,
    log_request,
    log_response,
    request_context,
    set_request_id,
    setup_logging,
)
from .metrics import (
    CallbackCollector,
    CompositeCollector,
    InMemoryCollector,
    MetricsCollector,
    NoOpCollector,
    RequestMetrics,
    get_metrics_collector,
    record_retry,
    set_metrics_collector,
    timed_request,
)
from .metrics_impl import (
    Counter,
    Gauge,
    Histogram,
    HistogramBucket,
    MetricValue,
    SimpleMetricsCollector,
)
from .pagination import AsyncPaginator, SyncPaginator
from .retry import RetryConfig, retry_with_backoff
from .security import (
    get_env_credential,
    mask_credential,
    redact_sensitive_data,
    validate_base_url,
    validate_id,
    validate_webhook_url,
)
from .telemetry import (
    RequestSpan,
    SpanKind,
    SpanStatusCode,
    TelemetryConfig,
    configure_telemetry,
    create_request_span,
    get_telemetry_config,
    is_telemetry_enabled,
    traced,
    with_tracing,
    with_tracing_async,
)

__all__ = [
    "AsyncPaginator",
    "SyncPaginator",
    "RetryConfig",
    "retry_with_backoff",
    # Security utilities
    "validate_id",
    "validate_base_url",
    "validate_webhook_url",
    "redact_sensitive_data",
    "get_env_credential",
    "mask_credential",
    # Logging utilities
    "LogConfig",
    "LogFormat",
    "LogLevel",
    "LoggerAdapter",
    "create_logger_adapter",
    "get_logger",
    "get_request_id",
    "log_error",
    "log_request",
    "log_response",
    "request_context",
    "set_request_id",
    "setup_logging",
    # Metrics utilities
    "CallbackCollector",
    "CompositeCollector",
    "Counter",
    "Gauge",
    "Histogram",
    "HistogramBucket",
    "InMemoryCollector",
    "MetricValue",
    "MetricsCollector",
    "NoOpCollector",
    "RequestMetrics",
    "SimpleMetricsCollector",
    "get_metrics_collector",
    "record_retry",
    "set_metrics_collector",
    "timed_request",
    # Telemetry utilities
    "TelemetryConfig",
    "SpanStatusCode",
    "SpanKind",
    "RequestSpan",
    "configure_telemetry",
    "get_telemetry_config",
    "is_telemetry_enabled",
    "create_request_span",
    "traced",
    "with_tracing",
    "with_tracing_async",
]
